adds check if file is not empty

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -42,6 +42,14 @@ mkdir -p $CREDENTIALS_DIR
 
 echo "--------> Injecting encrypted credentials..."
 /app/vendor/1password/bin/op document get --force --out-file $CREDENTIALS_DIR/credentials.yml.enc --vault $CREDENTIALS_VAULT $CREDENTIALS_ITEM
+if [[ ! -s $CREDENTIALS_DIR/credentials.yml.enc ]]; then
+  echo "ERROR: The credentials file is empty or does not exist."
+  exit 1
+fi
 
 echo "--------> Injecting rails master key..."
 /app/vendor/1password/bin/op read --force --out-file $CREDENTIALS_DIR/master.key op://$CREDENTIALS_VAULT/$CREDENTIALS_ITEM/RAILS_MASTER_KEY
+if [[ ! -s $CREDENTIALS_DIR/master.key ]]; then
+  echo "ERROR: The rails master key file is empty or does not exist."
+  exit 1
+fi
